Button and alert
manujagobind/pleasant-ui pull request #2
Opened 2022-02-02 18:41 UTC by manujagobind

**Summary**

This change adds the following:
- Set up initial directory structure for the component library
- Initial set of styling for core design aspects to be used across multiple components
- Styling for buttons component
- Documentation for buttons component
- Styling for alerts component
- Documentation for alerts component
- Index page to capture the list of all components

**Third Party Software Used**

This change makes use of the following external code:
- Uses [FontAwesome v5.15](https://fontawesome.com/v5.15/icons) for icons
- Uses [HighlightJS](https://highlightjs.org/) for code highlighting in the documentation pages

**View Live**
Please refer to the Netlify section below for the preview link.

2022-02-03 07:31 UTC, shrushti2000 reviewed
Looks good to me. You can add alerts with close buttons and floating action buttons too.

2022-02-03 12:11 UTC, manujagobind commented
> shrushti2000

Hey, thanks @shrushti2000 for the review. For now I'm only restricting to HTML and CSS. Didn't add close option as it requires JS.

2022-02-03 13:55 UTC, HarshnaNHaswani commented on src/button/button.html
> +        </section>
If you want to link the button to something, nest the `anchor` inside the `button` and give the necessary classes to the button. Otherwise, it is not a button. It is just an `<a>` that looks like a `<button>` and will not have the default properties of a button

2022-02-03 13:56 UTC, HarshnaNHaswani approved these changes

2022-02-03 14:00 UTC, HarshnaNHaswani commented on src/pages/button.html
> +        </section>
This can be treated as a second example/ sub-category for icon buttons. Just tell your user what changes you made in the icon tag to get this result (change: icon, color/background-color/outline color)

2022-02-03 14:03 UTC, HarshnaNHaswani approved these changes

2022-02-03 14:14 UTC, HarshnaNHaswani requested changes
It's awesome that you have followed semantic tags almost everywhere. Please give the suggestions I mentioned a thought before proceeding

2022-02-03 14:14 UTC, HarshnaNHaswani commented on src/styles/variables.css
>      --ink-green: #14c2ad;
Use a standard green for success. Familiarity helps. This turquoise bluish color is quite sharp and the text clarity is a bit low. You can use the dev tool's inspector to check whether the contrast between the text and the background is agreeable. Choose your colors wisely

2022-02-03 14:14 UTC, HarshnaNHaswani commented on src/pages/alert.html
> +    &lt;/div&gt;
format code here

2022-02-04 16:56 UTC, manujagobind commented on src/pages/alert.html
> +    &lt;/div&gt;
Hey @HarshnaNHaswani - if you're referring to this part of code being on the left of the page - then it's intentional. The `pre` tags remembers the spaces. If I move this section to the right then that extra space will show up in my code container as well in the docs.

2022-02-04 17:01 UTC, manujagobind commented on src/styles/variables.css
>      --ink-green: #14c2ad;
I haven't worked on the typography yet. Most of the colors I've selected are from the ones used in [this site](https://flutter.dev). Maybe when I work on typography things would start looking better. 

Regarding green color, I'll check. Thanks.

2022-02-04 20:19 UTC, HarshnaNHaswani commented on src/pages/alert.html
> +    &lt;/div&gt;
My mistake, I forgot. Sorry!

2022-02-04 20:20 UTC, HarshnaNHaswani commented on src/styles/variables.css
>      --ink-green: #14c2ad;
I'm talking about the clash between the text color and background color.

2022-02-04 20:21 UTC, HarshnaNHaswani commented on src/styles/variables.css
>      --ink-green: #14c2ad;
Thanks for looking into the suggestions and responding!

2022-02-05 15:51 UTC, manujagobind commented
Hey @HarshnaNHaswani, @shrushti2000 - have addressed the comments.

@HarshnaNHaswani - regarding the contrast b/w text and background, I'll check that once I work on typography.

2022-02-05 17:32 UTC, merged