Image and Input
manujagobind/pleasant-ui pull request #3
Opened 2022-02-05 17:38 UTC by manujagobind

**Summary**

This change adds the following:
- Styling for responsive images
- Documentation for responsive images
- Styling for inputs component
- Documentation for inputs component
- Updates index page with new components

**Third Party Software Used**

This change makes use of the following external code:
- Uses [HighlightJS](https://highlightjs.org/) for code highlighting in the documentation pages

**View Live**
Please refer to the Netlify section below for the preview link.

2022-02-07 14:55 UTC, viru2001 requested changes
Good work . I suggested some minor changes which you can do.

Also , use generic names for CSS variables instead of using color names itself for variable

2022-02-07 14:55 UTC, viru2001 commented on src/pages/image.html
> +      href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/11.4.0/styles/default.min.css">
you can import this in css if possible

2022-02-07 14:55 UTC, viru2001 commented on src/pages/image.html
> +                <div class="container-flex demo">
you can remove the `overflow : scroll` from demo

2022-02-07 14:55 UTC, viru2001 commented on src/pages/image.html
> +                    <img src="https://picsum.photos/300/300" alt="Sample image" class="img-responsive img-round">
you can add same height and width in img-round class.
```css
.img-round{
   height : 10rem;
   width:10rem;
}
```

2022-02-07 14:55 UTC, viru2001 commented on src/pages/input.html
> +    <link rel="stylesheet" href="../styles/input.css">
you should import your component css files in main css

2022-02-07 14:55 UTC, viru2001 commented on src/pages/input.html
> +                        <input type="text" name="demo2" id="demo2" placeholder="Input Warning">
you can give good proper name to `name` and `id`

2022-02-07 14:55 UTC, viru2001 commented on src/pages/input.html
> +                        <input type="text" name="demo2" id="demo2" placeholder="Input Warning">
value of `for` and `id` should be same

2022-02-07 14:55 UTC, viru2001 commented on src/pages/input.html
> +                        <input type="text" name="demo3" id="demo2" placeholder="Input Error">
`id` should be unique for each tag

2022-02-07 17:30 UTC, manujagobind commented on src/pages/image.html
> +                <div class="container-flex demo">
Hey Viresh - the demo container has a fixed max-width but content can take more space than that. This can be seen in effect in the docs for buttons component.

2022-02-07 17:37 UTC, manujagobind commented on src/pages/image.html
> +                    <img src="https://picsum.photos/300/300" alt="Sample image" class="img-responsive img-round">
Hey Viresh - thanks. I did not add any height or width because I wanted the image to adjust based on the container height and width. I don't know what fixed height/width would be appropriate.

2022-02-07 17:38 UTC, manujagobind commented
Thanks for the review @viru2001 - I've made the changes as suggested. For some, I've added comments above on why I did the other way.

2022-02-08 14:30 UTC, darshandamre reviewed
i think this is good to merge

2022-02-08 14:31 UTC, darshandamre approved these changes

2022-02-08 14:37 UTC, manujagobind commented
Thanks @darshandamre.

2022-02-08 14:37 UTC, merged